language: python
python:
  - "2.7"
env:
  global:
  - secure: WMVopO2bd6yvxE8z+3QnqZXjFzjnKZma9EqpqAjUYKNd20KcqTCJYdBU7oDdnKa+DFeGEeMZr9Mi+KFr48rRwbeF4jS2anMShO0Wdo3m9rr3ZoORQSWFCKq0zgm3XUHc5h+T9pK6fhJS7IjTkc3IFhGdZv7EB0Frmv8q2mru0Rmmszk4rgIiBhGvsgoYhY06i9BxZcsE8gLHkYmovoJ33e/5qJvtXavcGWW8qq/3Qwr3rK3SF9nBwe8mKZBx/fLO6jVCwtj4Kityp5pJqGbsXv2N8UW2/yx5mTyBoEmKnHuLbyaiS18bM15XTITsJNWVgOOHnSZ8FOcvkdr+4ziYtcxQqxB8Hlbr26Kt7qoaTvPuuZMDo07AcBOvoZrdQNyS8bddG3WJyaoePmOlohYCB4feUnemt01AXvupQa1mgYx/dwGnCpGHX16i08Aj2AIR1Ju+UcYyiHNtTnWP5hk8TSa8ZKLIhRF+e8eqiaX2FIrmzXryPpJtUHnv8FA2CcUV7in2WODR6+URladfP8Efio3qKsbm3DiOh63ug4v5W+/ZpfHvhzd8Zt0yEMWLl1YKLJNd2DXklh1DOfPaeN/E9JFheqtvZDn98S1MUQQ+EjtcslErNc6Pq06+N86cHlRCO9BawMcfXW84bnGySDSzhwN0aAjfxoNF/PiLE8jh1jk=
  - secure: UsRLtAxcFuxcf5+yrNLebEZe1AA4H0q1esPLoHln0vbkaBHqQbzoiFPOlaK9Jo74MHkLsIFyRsAuKlw1ZYICzaihET2ssYwKBUNe/8KeBFj3rz9ZGDMLQ7lEtVWA8gkJDNeIDySsnLgdhLJT4imaBHHo06FAV2k41iqwcU8RtURDzxSaGE5BXii2oN7IF01MmaLm9QOC0QjD0COUAGqyKC5wMT/v2GkSvWW9lRZAyY0sbhcuWF5UBzKKHJ2X36K9+ebFO9fGf6Dl/93QoTu01nnh1BXIG/xlNOP3/76z4bZkZjwnbUDs5kSR7qxYM1bEYVAjW5HTe28yf8eSzyPthRe8DPm2DFJXFYZWBJ6mjzSUiXNi1JgRceVs8rdUMxaM96J/4lT87U9wuXju8VqmCh73Ysy1jy3JK+IbOC3Qnlr9p9WOtBZdSf7IeUtj7aw/JdD/PKbiS84yCb4NE5MO3FsOqRcYFjKrvtBbpOPBVkVJ21RDncITKwEUYWDLNMazCh1gc11YqZigc7DtsMTi9S0bUNmWxtnVAGclASBbHB/Z6TJsHovfrxbDzRB+A60fLk9b0QRcXOdexlSHWjXSAbCbiA8OwZwcDnQ8Puko01xyL1f+8BfzJOqC5xn6IUQvDpn/VV/uHBMBJUN/76KgW3hNNz6GQlelC5z6ATgGO04=
install: pip install -r requirements_travis.txt
script: python -m pytest tests/
before_deploy:
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
deploy:
  - provider: script
    script: make env="sandbox" state="DISABLED" deploy
    on:
      branch: develop
  - provider: script
    script: make env="staging" state="DISABLED" deploy
    on:
      branch: staging
  - provider: script
    script: make env="prod" state="ENABLED" deploy
    on:
      tags: true
